from __future__ import annotations

from .exam_perdix_cases import (
    Exam_PERDIX_4_Sided_Polygon,
    Exam_PERDIX_5_Sided_Polygon,
    Exam_PERDIX_6_Sided_Polygon,
    Exam_PERDIX_Annulus,
    Exam_PERDIX_Arrowhead,
    Exam_PERDIX_Cairo_Penta_Tiling,
    Exam_PERDIX_Circle,
    Exam_PERDIX_Cross,
    Exam_PERDIX_Curved_Arm_Mix,
    Exam_PERDIX_Curved_Arm_Quad,
    Exam_PERDIX_Curved_Arm_Tri,
    Exam_PERDIX_Disk_Tri,
    Exam_PERDIX_Ellipse,
    Exam_PERDIX_Ellipse_Tri_Fine,
    Exam_PERDIX_Hepta_Penta_Tiling,
    Exam_PERDIX_Hexagonal_Tiling,
    Exam_PERDIX_Hexagon,
    Exam_PERDIX_Honeycomb,
    Exam_PERDIX_Hyperbolic_Paraboloid_Quad,
    Exam_PERDIX_Hyperbolic_Paraboloid_Tri,
    Exam_PERDIX_L_Shape_42bp,
    Exam_PERDIX_L_Shape_63bp,
    Exam_PERDIX_L_Shape_84bp,
    Exam_PERDIX_L_Shape_Irregular,
    Exam_PERDIX_L_Shape_Tri,
    Exam_PERDIX_Lotus,
    Exam_PERDIX_N_Polygon,
    Exam_PERDIX_N_Polygon_Mesh,
    Exam_PERDIX_Octagon,
    Exam_PERDIX_Octagon_Cross_1,
    Exam_PERDIX_Octagon_Cross_2,
    Exam_PERDIX_Pentagon,
    Exam_PERDIX_Plate_3x4,
    Exam_PERDIX_Plate_Distorted_Quad,
    Exam_PERDIX_Plate_Distorted_Tri,
    Exam_PERDIX_Plumeria,
    Exam_PERDIX_Pump_Eng,
    Exam_PERDIX_Pump_Quad,
    Exam_PERDIX_Pump_Tri,
    Exam_PERDIX_Prismatic_Penta_Tiling,
    Exam_PERDIX_Quarter_Circle,
    Exam_PERDIX_Quarter_Circle_Tri,
    Exam_PERDIX_Quarter_Hemi_Hole,
    Exam_PERDIX_Rhombic_Tiling,
    Exam_PERDIX_S_Shape_Eng,
    Exam_PERDIX_S_Shape_Quad,
    Exam_PERDIX_S_Shape_Tri,
    Exam_PERDIX_Small_House_Quad,
    Exam_PERDIX_Small_House_Tri,
    Exam_PERDIX_Square,
    Exam_PERDIX_Star,
    Exam_PERDIX_Stickman,
    Exam_PERDIX_Triangle,
    Exam_PERDIX_Wheel,
    Exam_PERDIX_circle_Tri_Fine,
    Exam_PERDIX_Controllable_Plate,
)


def select_exam_prob(sel: int, prob, geom) -> None:
    mapping = {
        1: Exam_PERDIX_Square,
        2: Exam_PERDIX_Honeycomb,
        3: Exam_PERDIX_Circle,
        4: Exam_PERDIX_Wheel,
        5: Exam_PERDIX_Ellipse,
        6: Exam_PERDIX_Rhombic_Tiling,
        7: Exam_PERDIX_Quarter_Circle,
        8: Exam_PERDIX_Cross,
        9: Exam_PERDIX_Arrowhead,
        10: Exam_PERDIX_Annulus,
        11: Exam_PERDIX_Cairo_Penta_Tiling,
        12: Exam_PERDIX_Lotus,
        13: Exam_PERDIX_Hexagonal_Tiling,
        14: Exam_PERDIX_Prismatic_Penta_Tiling,
        15: Exam_PERDIX_Hepta_Penta_Tiling,
        16: Exam_PERDIX_4_Sided_Polygon,
        17: Exam_PERDIX_5_Sided_Polygon,
        18: Exam_PERDIX_6_Sided_Polygon,
        19: Exam_PERDIX_L_Shape_42bp,
        20: Exam_PERDIX_L_Shape_63bp,
        21: Exam_PERDIX_L_Shape_84bp,
        22: Exam_PERDIX_Curved_Arm_Quad,
        23: Exam_PERDIX_Curved_Arm_Tri,
        24: Exam_PERDIX_Curved_Arm_Mix,
    }
    if sel not in mapping:
        raise ValueError("Selected pre-defined geometry not supported.")
    mapping[sel](prob, geom)
